### ISSUE TITLE
focuser

### ISSUE THREAD

**Issue by digitaloutlets** [cytan299/etx125_electric_focuser#2]
Not an issue..The unit works great per your plans!

![focuser](https://user-images.githubusercontent.com/40837801/42738538-5164172c-8853-11e8-996b-2be6910a83c9.jpg)
![focuser1](https://user-images.githubusercontent.com/40837801/42738545-67e8d5fa-8853-11e8-8f28-726fc735524f.jpg)
![focuser2](https://user-images.githubusercontent.com/40837801/42738550-8771a5a0-8853-11e8-9570-0600a376486c.jpg)

**Comment by cytan299** [comment]
Looks great! Thanks for posting.
